# Generated by Django 3.2.7 on 2021-09-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210928_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangepostdeliveryinfo',
            name='book1author',
        ),
        migrations.RemoveField(
            model_name='exchangepostdeliveryinfo',
            name='book1title',
        ),
        migrations.RemoveField(
            model_name='exchangepostdeliveryinfo',
            name='book2author',
        ),
        migrations.RemoveField(
            model_name='exchangepostdeliveryinfo',
            name='book2title',
        ),
        migrations.AddField(
            model_name='exchangepostdeliveryinfo',
            name='book1',
            field=models.ForeignKey(default='100000000', on_delete=django.db.models.deletion.CASCADE, related_name='book1', to='posts.exchangepost'),
        ),
        migrations.AddField(
            model_name='exchangepostdeliveryinfo',
            name='book2',
            field=models.ForeignKey(default='200000000', on_delete=django.db.models.deletion.CASCADE, related_name='book2', to='posts.exchangepost'),
        ),
    ]
