# Generated by Django 3.2.7 on 2021-09-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210928_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangepostdeliveryinfo',
            name='book1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book1', to='posts.exchangepost'),
        ),
        migrations.AlterField(
            model_name='exchangepostdeliveryinfo',
            name='book2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book2', to='posts.exchangepost'),
        ),
    ]
