# Generated by Django 3.2.7 on 2021-09-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_postimage_sellpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangepost',
            name='catagory',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
