# Generated by Django 3.2.7 on 2021-09-16 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('edition', models.PositiveIntegerField(blank=True)),
                ('publisher', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangePost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('prefered_book', models.ManyToManyField(to='posts.PreferedBook')),
            ],
            bases=('posts.post',),
        ),
    ]
