# Generated by Django 3.2.7 on 2021-09-16 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_exchangepost_preferedbook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreferedBook',
            new_name='PreferredBook',
        ),
    ]
