# Generated by Django 3.2.7 on 2021-09-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_preferedbook_preferredbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangepost',
            name='prefered_book',
        ),
        migrations.AddField(
            model_name='exchangepost',
            name='prefered_books',
            field=models.ManyToManyField(related_name='exchange_post', to='posts.PreferredBook'),
        ),
    ]
