# Generated by Django 3.2.6 on 2021-09-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210916_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edition',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='preferredbook',
            name='edition',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='preferredbook',
            name='publisher',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
