# Generated by Django 3.2.7 on 2021-09-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='blog_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
