# Generated by Django 3.2.7 on 2021-09-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210914_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog_id',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
